name: Bernard
version: 0.0.1
author: Hermanos
main: net.hermanos.ac.Bernard
load: STARTUP
depend: [ProtocolLib]
commands:
  alerts:
    description: Toggles off and on alerts
  autoban:
    description: Stops autobanning
  bernard:
    description: Bernard root command
    aliases: [anticheat] 
  getlog:
    description: Get a player's log!
permissions:
  daedalus.staff:
    description: Gives access to staff
    default: op
  daedalus.admin:
    description: Gives access to admin
    default: op
  daedalus.log:
    description: Gives access to /getlog
    default: op
  daedalus.bypass:
    default: false
    description: Bypass node.